// src/content/assets.ts
import { AssetItem } from '@/types/content';

export const assetCatalog: AssetItem[] = [
  {
    id: 'AST-01',
    title: 'XEVRYN Orbit Icons Pack',
    category: 'icons',
    format: 'SVG Vector (8 Ikon)',
    dimensionOrSize: '800 × 600 px · 4.8 KB',
    license: 'MIT (Bebas untuk Personal & Komersial)',
    source: 'Koleksi Orisinal XEVRYN Space Hub',
    description: 'Kumpulan 8 ikon vektor kosmik orisinal: Orbit Ring, Rocket Scout, Cosmic Helmet, Orbital Satellite, Zero-G Coffee Cup, Telescope, Asteroid Core, dan Solar Pulsar.',
    downloadUrl: '/assets/downloads/orbit-icons-pack.svg',
    previewUrl: '/assets/downloads/orbit-icons-pack.svg',
    tags: ['SVG', 'Icons', 'Vector', 'Space', 'Clean'],
  },
  {
    id: 'AST-02',
    title: 'Cosmic Starfield & Constellation Pattern',
    category: 'patterns',
    format: 'SVG Seamless Pattern',
    dimensionOrSize: '400 × 400 px · 2.4 KB',
    license: 'MIT / CC0 Universal',
    source: 'Koleksi Orisinal XEVRYN Space Hub',
    description: 'Pola latar belakang bintang dan garis konstelasi langit malam dengan pendaran nebula halus. Ringan, skalabel, dan siap dijadikan pola pengulangan CSS background.',
    downloadUrl: '/assets/downloads/cosmic-starfield-pattern.svg',
    previewUrl: '/assets/downloads/cosmic-starfield-pattern.svg',
    tags: ['Pattern', 'Stars', 'Constellation', 'Seamless', 'CSS'],
  },
  {
    id: 'AST-03',
    title: 'XEVRYN Deep Space Horizon Wallpaper',
    category: 'wallpapers',
    format: 'Scalable SVG Vector (16:9)',
    dimensionOrSize: '1920 × 1080 px · 3.9 KB',
    license: 'Creative Commons CC-BY 4.0',
    source: 'Koleksi Orisinal XEVRYN Space Hub',
    description: 'Wallpaper vektor ruang angkasa resolusi tinggi menampilkan gradasi nebula ganda (cyan & magenta), matahari keemasan, planet bercincin, dan horizon lengkungan fajar kosmik.',
    downloadUrl: '/assets/downloads/xevryn-cosmic-wallpaper.svg',
    previewUrl: '/assets/downloads/xevryn-cosmic-wallpaper.svg',
    tags: ['Wallpaper', '1080p', 'Vector', 'Cosmic', 'Desktop'],
  },
  {
    id: 'AST-04',
    title: 'XEVRYN Geometric Monograms & Wordmark',
    category: 'ui',
    format: 'SVG Vector Suite',
    dimensionOrSize: '600 × 450 px · 3.1 KB',
    license: 'MIT (Bebas Modifikasi)',
    source: 'Koleksi Orisinal XEVRYN Space Hub',
    description: 'Kumpulan logo geometris monokrom dan aksen cyan: Diamond X, Orbital Node, Hex Crest, serta typographic wordmark untuk identitas situs digital bertema fiksi ilmiah.',
    downloadUrl: '/assets/downloads/xevryn-brand-marks.svg',
    previewUrl: '/assets/downloads/xevryn-brand-marks.svg',
    tags: ['Monogram', 'Branding', 'Typography', 'Logo', 'Minimal'],
  },
];
