// src/content/celestialObjects.ts

import { CelestialObjectMeta } from '@/types/universe';

export const CELESTIAL_OBJECTS: CelestialObjectMeta[] = [
  {
    id: 'obj-sun-core',
    name: 'XEVRYN CORE',
    category: 'CORE',
    subtitle: 'Central Stellar Anchor & Fusion Core',
    position: [-8.5, 5.5, -22.0],
    radius: 3.5,
    safeDistance: 8.5,
    sectionId: 'hero',
    description: 'Bintang pusat semesta digital XEVRYN. Memancarkan gravitasi naratif, partikel angin surya, dan sumber pencahayaan kosmik utama.',
    tags: ['Stellar Core', 'Light Source', 'Anchor'],
    status: 'ACTIVE FUSION',
    actionLabel: 'INSPECT CORE',
    actionTarget: '#hero',
  },
  {
    id: 'obj-planet-cosmic',
    name: 'XEVRYN PORTFOLIO V2',
    category: 'PROJECT',
    subtitle: 'Primary Rocky Planet & Orbital Moon',
    position: [1.95, 0.0, 0.0],
    radius: 1.5,
    safeDistance: 4.8,
    slug: 'xevryn-cosmic-portfolio',
    sectionId: 'work',
    description: 'Dunia bebatuan utama dengan kawah geologis alami, atmosfer grazing glow tipis, dan bulan pengorbit sinkron. Pondasi arsitektur Three.js + GSAP.',
    tags: ['React 19', 'Three.js', 'GSAP', 'WebGL'],
    status: 'CONFIRMED',
    actionLabel: 'EXPLORE PROJECT',
    actionTarget: '#work/xevryn-cosmic-portfolio',
  },
  {
    id: 'obj-planet-ocean',
    name: 'XEVRYN CAMPUS',
    category: 'PROJECT',
    subtitle: 'Oceanic World & Cloud Canopy',
    position: [6.2, 1.8, -9.5],
    radius: 1.1,
    safeDistance: 4.2,
    slug: 'xevryn-campus',
    sectionId: 'work',
    description: 'Dunia samudera dengan daratan organik, batimetri laut dalam, dan lapisan awan kumulus terpisah. Representasi platform produktivitas akademik kampus.',
    tags: ['Academic Workspace', 'Productivity', 'TypeScript'],
    status: 'CONFIRMED',
    actionLabel: 'EXPLORE PROJECT',
    actionTarget: '#work/xevryn-campus',
  },
  {
    id: 'obj-planet-red',
    name: 'MARKETRA MITTA',
    category: 'PROJECT',
    subtitle: 'Red Planet & Valles Marineris Canyon',
    position: [-6.2, -6.5, -11.5],
    radius: 1.3,
    safeDistance: 4.6,
    slug: 'marketra',
    sectionId: 'work',
    description: 'Planet merah dengan ngarai raksasa dan tudung es kutub. Merepresentasikan etalase digital dan platform web interaktif Marketra.',
    tags: ['Web Application', 'Interactive Catalog', 'Next.js'],
    status: 'CONFIRMED',
    actionLabel: 'EXPLORE PROJECT',
    actionTarget: '#work/marketra',
  },
  {
    id: 'obj-planet-gas',
    name: 'UCAPAN BUAT KAMU',
    category: 'PROJECT',
    subtitle: 'Gas Giant with Swirling Amber Storms',
    position: [8.5, -13.2, -15.0],
    radius: 2.8,
    safeDistance: 7.2,
    slug: 'ucapan-buat-kamu',
    sectionId: 'more-projects',
    description: 'Planet gas raksasa dengan pita turbulen atmosfer ambar dan pusaran badai oval. Menampung web interaktif personal dengan proteksi privasi.',
    tags: ['Interactive Micro-Experience', 'Animation', 'PII Protected'],
    status: 'CONFIRMED',
    actionLabel: 'EXPLORE PROJECT',
    actionTarget: '#work/ucapan-buat-kamu',
  },
  {
    id: 'obj-planet-ring',
    name: 'RETAILLAB',
    category: 'PROJECT',
    subtitle: 'Ringed World & Cassini Division',
    position: [-7.5, -18.5, -14.0],
    radius: 1.6,
    safeDistance: 5.8,
    slug: 'retaillab',
    sectionId: 'work',
    description: 'Dunia cincin elegan dengan zona partikel es Ring A, Ring B, dan celah Cassini transparan. Purwarupa POS dan transaksi ritel interaktif.',
    tags: ['Retail POS', 'Catalog Architecture', 'TypeScript'],
    status: 'CONFIRMED',
    actionLabel: 'EXPLORE PROJECT',
    actionTarget: '#work/retaillab',
  },
  {
    id: 'obj-sat-alpha',
    name: 'CAMPUS WHATSAPP BOT',
    category: 'PROJECT',
    subtitle: 'Orbital Telemetry Relay Alpha',
    position: [-2.4, -5.8, -1.2],
    radius: 0.6,
    safeDistance: 2.8,
    slug: 'campus-whatsapp-bot',
    sectionId: 'more-projects',
    description: 'Satelit komunikasi pengorbit rendah yang menangani otomatisasi antrean pesan kampus, pengingat jadwal, dan webhook asisten.',
    tags: ['Node.js', 'WhatsApp Web API', 'Automation'],
    status: 'CONFIRMED',
    actionLabel: 'EXPLORE BOT',
    actionTarget: '#work/campus-whatsapp-bot',
  },
  {
    id: 'obj-sat-beta',
    name: 'XEVRYN ASSETS',
    category: 'PROJECT',
    subtitle: 'Orbital Signal Relay Beta',
    position: [2.6, -15.5, -2.2],
    radius: 0.5,
    safeDistance: 2.6,
    slug: 'xevryn-assets',
    sectionId: 'more-projects',
    description: 'Satelit pemancar kurasi aset vektor SVG asli, monograms, dan pola kosmik siap unduh.',
    tags: ['SVG Library', 'Original Design', 'Vector Assets'],
    status: 'CONFIRMED',
    actionLabel: 'EXPLORE ASSETS',
    actionTarget: '#asset-station',
  },
  {
    id: 'obj-media3-archive',
    name: 'MEDIA 3 VAULT',
    category: 'ARCHIVE',
    subtitle: 'SMAN 3 Sumedang Creative Film Archive',
    position: [2.0, -7.5, -6.5],
    radius: 1.0,
    safeDistance: 3.8,
    sectionId: 'media3-archive',
    description: 'Arsip seluloid sinematik ekstrakurikuler Media 3 SMAN 3 Sumedang: produksi film pendek, video dokumenter, dan media kreatif.',
    tags: ['Film Production', 'Creative Media', 'SMAN 3 Sumedang'],
    status: 'VERIFIED',
    actionLabel: 'VIEW ARCHIVE',
    actionTarget: '#media3-archive',
  },
  {
    id: 'obj-coffee-street',
    name: 'COFFEE STREET ORBIT',
    category: 'EXPERIENCE',
    subtitle: '11/12 Coffe Street Operational Station',
    position: [-3.2, -4.5, -5.0],
    radius: 0.9,
    safeDistance: 3.6,
    sectionId: 'experience',
    description: 'Pangkalan orbital nyata: pengalaman Barista & Kasir di 11/12 coffe street Sumedang. Pelayanan cepat, transaksi, dan kerja tim.',
    tags: ['Barista', 'Cashier', 'Real-world Operations'],
    status: 'VERIFIED',
    actionLabel: 'VIEW EXPERIENCE',
    actionTarget: '#experience',
  },
  {
    id: 'obj-roblox-station',
    name: 'ROBLOX PLAYGROUND',
    category: 'LAB',
    subtitle: 'Asteroid Belt Sandbox & Luau Core',
    position: [0.0, -10.0, -12.0],
    radius: 1.4,
    safeDistance: 4.5,
    slug: 'roblox-projects',
    sectionId: 'roblox',
    description: 'Laboratorium eksplorasi scripting Luau modular, arsitektur game 3D masa depan, dan mini-game Asteroid Dodge.',
    tags: ['Roblox Studio', 'Luau Scripting', 'Physics Sandbox'],
    status: 'EXPERIMENTING',
    actionLabel: 'ENTER LAB',
    actionTarget: '#roblox-lab',
  },
  {
    id: 'obj-spacewalk-astronaut',
    name: 'EVA EXPLORER',
    category: 'NAVIGATION',
    subtitle: 'Autonomous Deep Space Spacewalker',
    position: [-3.2, -2.8, -4.5],
    radius: 0.45,
    safeDistance: 2.2,
    sectionId: 'hero',
    description: 'Astronaut penjelajah kosmik yang mengapung di gravitasi mikro. Klik untuk menerima sapaan telemetri orbital.',
    tags: ['Spacewalk', 'Telemetry', 'Easter Egg'],
    status: 'IN ORBIT',
    actionLabel: 'HAIL ASTRONAUT',
    actionTarget: '#hero',
  },
];

export function getCelestialObjectById(id: string): CelestialObjectMeta | undefined {
  return CELESTIAL_OBJECTS.find((obj) => obj.id === id);
}
