// src/content/hubStations.ts
import { HubStation } from '@/types/content';

export const hubStations: HubStation[] = [
  {
    id: 'portfolio',
    name: 'Orbit Utama',
    route: '/',
    tagline: 'Portofolio Kosmik',
    description: 'Pusat perjalanan tata surya 11 section, showcase proyek web, eksplorasi keahlian, dan kontak resmi.',
    symbol: '🪐',
    color: '#38bdf8',
    planetCoord: { x: 1.6, y: -0.2, z: 3.2 },
  },
  {
    id: 'roblox-lab',
    name: 'Roblox Lab',
    route: '#roblox-lab',
    tagline: 'Stasiun Eksperimen Luau',
    description: 'Eksplorasi pengembangan Roblox dan dasar scripting Lua/Luau dalam suasana stasiun antariksa.',
    symbol: '💠',
    color: '#c084fc',
    planetCoord: { x: 2.6, y: -8.2, z: 3.2 },
  },
  {
    id: 'atomic-hub',
    name: 'Atomic Hub',
    route: '#atomic-hub',
    tagline: 'Ruang Kontribusi Kreatif',
    description: 'Galeri hologram kontribusi sebagai Content Creator & Pemasaran untuk Atomic Roblox Hub.',
    symbol: '⚡',
    color: '#ec4899',
    planetCoord: { x: -2.2, y: -3.2, z: 3.0 },
  },
  {
    id: 'playground',
    name: 'Playground',
    route: '#playground',
    tagline: 'Simulasi & Mini Game',
    description: 'Game Asteroid Dodge, inspeksi planet interaktif, dan simulasi partikel kosmik langsung di browser.',
    symbol: '🚀',
    color: '#f59e0b',
    planetCoord: { x: 0.0, y: -7.5, z: 3.8 },
  },
  {
    id: 'asset-station',
    name: 'Asset Station',
    route: '#asset-station',
    tagline: 'Katalog Aset Desain',
    description: 'Unduh paket ikon orbit SVG, pola kosmik, dan wallpaper ruang angkasa orisinal berlisensi bebas.',
    symbol: '📦',
    color: '#10b981',
    planetCoord: { x: 2.2, y: -14.8, z: 3.4 },
  },
  {
    id: 'devlog',
    name: 'Devlog',
    route: '#devlog',
    tagline: 'Catatan Arsitektur',
    description: 'Catatan faktual di balik perancangan Three.js, koreografi GSAP, dan evolusi Space Hub.',
    symbol: '📜',
    color: '#6366f1',
    planetCoord: { x: -2.8, y: -11.5, z: 3.6 },
  },
  {
    id: 'orbit-cafe',
    name: 'Orbit Café',
    route: '#orbit-cafe',
    tagline: 'Ruang Santai & Fokus',
    description: 'Kedai kopi di orbit dengan pemandangan planet, timer fokus anti-drift, dan ambience santai.',
    symbol: '☕',
    color: '#d97706',
    planetCoord: { x: 0.0, y: -2.0, z: 4.5 },
  },
];
