// src/content/projects.ts
import { ProjectContent } from '@/types/content';

export const projectsContent: ProjectContent[] = [
  {
    id: 'PRJ-COSMIC',
    slug: 'xevryn-cosmic-portfolio',
    title: 'XEVRYN Cosmic Portfolio V2',
    summary: 'Portofolio personal interaktif berstandar Awwwards dengan latar belakang WebGL 3D, koreografi kamera GSAP, dan arsitektur aksesibilitas tinggi.',
    role: 'Creative Developer & Architect',
    year: '2026',
    tags: ['React 19', 'TypeScript', 'Three.js', 'GSAP', 'WebGL', 'Vanilla CSS'],
    coverImage: '/images/project-01.webp',
    galleryImages: ['/images/project-01-detail1.webp'],
    problem: 'Banyak website portofolio interaktif yang terlalu berat, merusak navigasi alami browser (scroll-jacking), atau tidak ramah pengguna layar sentuh dan pembaca layar.',
    solution: 'Membangun arsitektur terpisah antara satu canvas WebGL persisten dengan interpolasi GSAP ScrollTrigger via mutable ref bridge, tanpa scroll-jacking eksternal.',
    features: [
      'Single persistent WebGL scene dengan tata surya prosedural',
      'Kontrak kepemilikan animasi GSAP ke Three.js useFrame',
      'Mode adaptif 3 tingkat: Full, Lite, dan Reduced Motion',
      'Fallback anggun 2D otomatis jika WebGL tidak didukung',
      'Terminal interaktif developer terintegrasi',
    ],
    challenge: 'Mengelola sinkronisasi framerate WebGL dan timeline scroll DOM tanpa memory leak dan menjaga LCP tetap di bawah 2.5 detik.',
    approach: 'Menerapkan one-way state flow lewat mutable ref, instancing mesh untuk asteroid, shader prosedural tekstur planet, dan debounce resize.',
    outcome: 'Pengalaman menjelajah kosmik yang mulus, stabil pada 60 FPS di desktop, serta ramah sentuhan mobile.',
    links: [
      { label: 'Jelajahi Tata Surya', url: '#hero', kind: 'demo' },
      { label: 'Repositori GitHub', url: 'https://github.com/xevryn16-creator/xevryn-cosmic-portfolio', kind: 'repo' },
    ],
    celestialType: 'sun',
    status: 'CONFIRMED',
  },
  {
    id: 'PRJ-CAMPUS',
    slug: 'xevryn-campus',
    title: 'Xevryn Campus',
    summary: 'Platform produktivitas dan ruang kerja akademik untuk mengelola jadwal perkuliahan, tugas kolaboratif, dan arsip referensi mahasiswa.',
    role: 'Full Stack Web Developer',
    year: '2025',
    tags: ['React', 'TypeScript', 'Productivity', 'Campus Workspace', 'Node.js'],
    coverImage: '/images/project-02.webp',
    galleryImages: ['/images/project-02-detail1.webp'],
    problem: 'Penyebaran informasi tugas dan jadwal kuliah yang terfragmentasi di berbagai grup obrolan menyulitkan manajemen waktu mahasiswa.',
    solution: 'Mengembangkan dashboard terpusat yang menggabungkan pelacak deadline, agenda harian terstruktur, dan ruang simpan materi mata kuliah.',
    features: [
      'Dashboard ringkasan tugas dan status tenggat waktu',
      'Kalender akademik interaktif dengan filter kategori',
      'Arsip materi perkuliahan dengan pencarian cepat',
      'Mode tampilan gelap ramah mata untuk belajar malam hari',
    ],
    challenge: 'Merancang arsitektur data lokal yang cepat dan responsif serta layout yang tetap nyaman diakses melalui smartphone.',
    approach: 'Komposisi komponen modular yang ringan dengan persistensi lokal dan state terisolasi.',
    outcome: 'Aplikasi ruang kerja kampus yang terstruktur dan mempermudah pemantauan tugas akademik.',
    links: [
      { label: 'Lihat Detail Proyek', url: '#work/xevryn-campus', kind: 'demo' },
    ],
    celestialType: 'ocean',
    status: 'CONFIRMED',
  },
  {
    id: 'PRJ-BOT',
    slug: 'campus-whatsapp-bot',
    title: 'Campus WhatsApp Bot',
    summary: 'Bot otomasi layanan pesan kampus berbasis WhatsApp untuk pengingat jadwal otomatis, kueri informasi akademik, dan notifikasi tugas.',
    role: 'Backend Developer & Automation Scripting',
    year: '2025',
    tags: ['Node.js', 'WhatsApp Web API', 'Automation', 'Cron', 'Webhook'],
    coverImage: '/images/project-05.webp',
    galleryImages: ['/images/project-05-detail1.webp'],
    problem: 'Keterlambatan pengumpulan tugas sering terjadi akibat mahasiswa melewatkan pengumuman penting di linimasa grup chat.',
    solution: 'Membangun bot otomatisasi WhatsApp yang mengirimkan pengingat personal dan merespons perintah teks secara instan.',
    features: [
      'Pengingat jadwal kuliah otomatis setiap pagi via cron scheduler',
      'Perintah interaktif seperti !jadwal, !tugas, dan !info',
      'Sistem antrian pesan untuk menghindari pemblokiran batas laju kirim',
      'Penyimpanan konfigurasi sederhana berbasis JSON / database ringan',
    ],
    challenge: 'Menjaga koneksi sesi WhatsApp tetap stabil dan menangani reconnect otomatis ketika jaringan terputus.',
    approach: 'Mengimplementasikan mekanisme heartbeat liveness check, auto-retry connection, dan modular handler per perintah.',
    outcome: 'Bot layanan otomatis yang membantu mengingatkan agenda perkuliahan secara konsisten tanpa intervensi manual.',
    links: [
      { label: 'Lihat Detail Proyek', url: '#work/campus-whatsapp-bot', kind: 'demo' },
    ],
    celestialType: 'satellite',
    status: 'CONFIRMED',
  },
  {
    id: 'PRJ-RETAIL',
    slug: 'retaillab',
    title: 'RetailLab',
    summary: 'Aplikasi platform simulasi dan manajemen pembelajaran ritel yang dirancang untuk kebutuhan praktikum kejuruan (SMK).',
    role: 'Frontend Developer',
    year: '2025',
    tags: ['Web App', 'Interactive UI', 'Education Tech', 'Retail Simulation'],
    coverImage: '/images/project-02.webp',
    galleryImages: ['/images/project-02-detail1.webp'],
    problem: 'Siswa kejuruan memerlukan media praktik simulasi transaksi ritel dan inventaris yang realistis tanpa harus menggunakan perangkat kasir mahal.',
    solution: 'Menerjemahkan alur operasional ritel nyata ke dalam antarmuka web interaktif yang mudah dipahami oleh siswa dalam proses belajar.',
    features: [
      'Simulasi transaksi POS (Point of Sale) kasir dengan struk virtual',
      'Manajemen stok barang masuk dan pembaruan otomatis',
      'Laporan omzet sesi praktikum secara visual',
    ],
    challenge: 'Menyajikan alur kalkulasi harga, potongan, dan stok barang yang langsung ter-update di layar secara realtime.',
    approach: 'Mendesain tata letak fungsional dengan form interaktif, simulasi transaksi kasir/stok, serta feedback visual langsung.',
    outcome: 'Aplikasi interaktif yang memfasilitasi simulasi skenario ritel secara visual dan terstruktur bagi siswa kejuruan.',
    links: [
      { label: 'Lihat Detail Proyek', url: '#work/retaillab', kind: 'demo' },
    ],
    celestialType: 'rocky',
    status: 'CONFIRMED',
  },
  {
    id: 'PRJ-UCAPAN',
    slug: 'ucapan-buat-kamu',
    title: 'Ucapan-Buat-Kamu',
    summary: 'Website hadiah dan ucapan personal interaktif dengan sentuhan animasi kartu, mikro-interaksi hangat, dan privasi penuh.',
    role: 'Creative Web Developer',
    year: '2024',
    tags: ['Creative Web', 'Interactive Experience', 'CSS Motion', 'Personal Gift'],
    coverImage: '/images/project-04.webp',
    galleryImages: ['/images/project-04-detail1.webp'],
    problem: 'Kartu ucapan digital konvensional cenderung statis dan kaku seperti gambar biasa tanpa rasa keintiman visual.',
    solution: 'Menghadirkan pengalaman membuka pesan personal yang berkesan melalui interaksi web yang lembut, hangat, dan interaktif.',
    features: [
      'Animasi pembuka amplop dan kartu pesan berlapis',
      'Mikro-interaksi klik responsif dengan efek konfeti lembut',
      'Desain estetis yang menjaga privasi penerima tanpa menyimpan data pribadi ke server publik',
    ],
    challenge: 'Memastikan animasi kartu bergerak halus di browser ponsel tanpa frame drop.',
    approach: 'Mengoptimalkan CSS hardware-accelerated transforms (translate3d, opacity) dan menghindari layout thrashing.',
    outcome: 'Media digital ekspresif untuk menyampaikan ucapan secara kreatif, personal, dan berkesan.',
    links: [
      { label: 'Lihat Detail Proyek', url: '#work/ucapan-buat-kamu', kind: 'demo' },
    ],
    celestialType: 'nebula_planet',
    status: 'CONFIRMED',
  },
  {
    id: 'PRJ-ROBLOX',
    slug: 'roblox-projects',
    title: 'Roblox Development & Luau Scripting',
    summary: 'Eksplorasi lingkungan 3D Roblox Studio, manipulasi physics part, mekanika interaktif, serta penulisan skrip fungsional dengan Luau.',
    role: 'Roblox Explorer & Scripting Hobbyist',
    year: '2024 - Sekarang',
    tags: ['Roblox Studio', 'Luau', '3D Environment', 'Event-Driven Logic'],
    coverImage: '/images/project-03.webp',
    galleryImages: ['/images/project-03-detail1.webp'],
    problem: 'Memahami bagaimana logika event-driven dan sinkronisasi client-server bekerja di lingkungan mesin game 3D real-time.',
    solution: 'Bereksperimen membuat ruang 3D, mekanika objek interaktif, dan skrip event sederhana di Roblox Studio.',
    features: [
      'Pembangunan set lingkungan 3D luar angkasa dan stasiun futuristik',
      'Skrip interaksi pintu otomatis, tombol pemicu, dan sistem teleport',
      'Eksplorasi modul script untuk manajemen state objek',
    ],
    challenge: 'Mempelajari perbedaan paradigma penulisan skrip Luau dibandingkan dengan JavaScript/TypeScript di web.',
    approach: 'Mempelajari dokumentasi resmi Roblox Creator Hub, menganalisis struktur part dan instance, serta berlatih membuat mekanika dari skala kecil.',
    outcome: 'Pemahaman praktis tentang logika game 3D, physics simulation, dan bahasa pemrograman Luau.',
    links: [
      { label: 'Eksplorasi Roblox Lab', url: '#roblox-lab', kind: 'demo' },
    ],
    celestialType: 'gas_giant',
    status: 'CONFIRMED',
  },
  {
    id: 'PRJ-MARKETRA',
    slug: 'marketra',
    title: 'Marketra / Marketra Mitta',
    summary: 'Aplikasi workspace riset terintegrasi yang menghadirkan alur onboarding terarah dan dashboard analisis data terstruktur.',
    role: 'Frontend Developer & UI Designer',
    year: '2025',
    tags: ['React', 'TypeScript', 'Workspace', 'Dashboard UI'],
    coverImage: '/images/project-01.webp',
    galleryImages: ['/images/project-01-detail1.webp'],
    challenge: 'Menyusun hierarki informasi pada dashboard multi-panel serta merancang onboarding yang memandu pengguna memahami alur riset tanpa rasa kewalahan.',
    approach: 'Mengembangkan sistem komponen modular dengan state management yang terstruktur, navigasi yang intuitif, dan visual feedback yang jelas.',
    outcome: 'Alur onboarding yang terarah dan antarmuka dashboard riset yang responsif di berbagai resolusi layar.',
    links: [
      { label: 'Lihat Detail Proyek', url: '#work/marketra', kind: 'demo' },
    ],
    celestialType: 'ringed',
    status: 'CONFIRMED',
  },
  {
    id: 'PRJ-ASSETS',
    slug: 'xevryn-assets',
    title: 'Xevryn Assets Library',
    summary: 'Koleksi terkurasi aset desain, token antarmuka, dan komponen reusable untuk mempercepat perancangan produk digital konsisten.',
    role: 'Design System & Asset Curator',
    year: '2024',
    tags: ['Design System', 'UI Assets', 'Design Tokens', 'Figma/Code'],
    coverImage: '/images/project-03.webp',
    galleryImages: ['/images/project-03-detail1.webp'],
    challenge: 'Membangun standardisasi token warna, tipografi, dan komponen UI yang konsisten serta mudah diadaptasi ke berbagai proyek.',
    approach: 'Menerapkan token arsitektural berskala dan dokumentasi spesifikasi komponen yang jelas untuk kemudahan penggunaan.',
    outcome: 'Perpustakaan aset terorganisir yang menjadi fondasi konsistensi desain di seluruh proyek digital.',
    links: [
      { label: 'Lihat Detail Proyek', url: '#work/xevryn-assets', kind: 'demo' },
      { label: 'Stasiun Unduh Aset', url: '#asset-station', kind: 'demo' },
    ],
    celestialType: 'rocky',
    status: 'CONFIRMED',
  },
];
