// src/content/skills.ts
import { SkillItem } from '@/types/content';

export const skillsContent: SkillItem[] = [
  // 1. DEVELOPMENT
  {
    id: 'SKL-DEV-REACT',
    label: 'React',
    category: 'development',
    badge: 'Confirmed',
    description: 'Pembangunan arsitektur antarmuka reaktif berbasis komponen modular, custom hooks, dan manajemen state modern.',
    projectIds: ['xevryn-cosmic-portfolio', 'xevryn-campus', 'marketra', 'retaillab'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-DEV-TS',
    label: 'TypeScript',
    category: 'development',
    badge: 'Confirmed',
    description: 'Penerapan type safety ketat, pemodelan data terstruktur, dan refactoring aman di seluruh codebase.',
    projectIds: ['xevryn-cosmic-portfolio', 'xevryn-campus', 'marketra', 'retaillab'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-DEV-JS',
    label: 'JavaScript (ES6+)',
    category: 'development',
    badge: 'Confirmed',
    description: 'Pemahaman mendalam tentang event loop, async/await, DOM manipulation, dan functional programming patterns.',
    projectIds: ['xevryn-cosmic-portfolio', 'campus-whatsapp-bot', 'ucapan-buat-kamu'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-DEV-NODE',
    label: 'Node.js',
    category: 'development',
    badge: 'Confirmed',
    description: 'Pengembangan backend runtime ringan, scripting bot otomatisasi, API service, dan tooling otomatis.',
    projectIds: ['campus-whatsapp-bot', 'xevryn-campus'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-DEV-THREE',
    label: 'Three.js & WebGL',
    category: 'development',
    badge: 'Confirmed',
    description: 'Penyusunan scene 3D, camera rig math, lighting, procedural textures, dan optimasi canvas WebGL.',
    projectIds: ['xevryn-cosmic-portfolio'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-DEV-HTMLCSS',
    label: 'HTML5 & Modern CSS',
    category: 'development',
    badge: 'Confirmed',
    description: 'Penyusunan struktur semantik HTML5, aksesibilitas ARIA, CSS custom properties (tokens), dan responsivitas fluida.',
    projectIds: ['xevryn-cosmic-portfolio', 'ucapan-buat-kamu', 'retaillab'],
    status: 'CONFIRMED',
  },

  // 2. CREATIVE MEDIA
  {
    id: 'SKL-CRT-FILM',
    label: 'Film Production',
    category: 'creative_media',
    badge: 'Confirmed',
    description: 'Pengalaman nyata dalam pra-produksi, pengambilan gambar lapangan, dan koordinasi tim di Media 3 SMAN 3 Sumedang.',
    projectIds: ['EXP-M3'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-CRT-MEDIA',
    label: 'Creative Media',
    category: 'creative_media',
    badge: 'Confirmed',
    description: 'Perancangan identitas visual, storytelling sinematik, dan penyajian materi publikasi kreatif.',
    projectIds: ['EXP-M3', 'M3-04'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-CRT-VIDEO',
    label: 'Video Editing',
    category: 'creative_media',
    badge: 'Confirmed',
    description: 'Penyuntingan video ritmis, pemotongan footage berurutan, sinkronisasi audio, dan pemilihan ambience warna.',
    projectIds: ['EXP-M3', 'M3-02'],
    status: 'CONFIRMED',
  },

  // 3. EXPLORING
  {
    id: 'SKL-EXP-AI',
    label: 'AI & LLM Workflows',
    category: 'exploring',
    badge: 'Exploring',
    description: 'Eksplorasi integrasi model AI, prompting rekayasa terstruktur, serta alur kerja asisten koding cerdas.',
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-EXP-AUTO',
    label: 'Automation',
    category: 'exploring',
    badge: 'Exploring',
    description: 'Pembuatan skrip otomatisasi pesan, webhook listener, dan otomasi alur kerja rutin kampus.',
    projectIds: ['campus-whatsapp-bot'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-EXP-SEC',
    label: 'Cybersecurity',
    category: 'exploring',
    badge: 'Learning',
    description: 'Mempelajari dasar keamanan aplikasi web, mitigasi kerentanan OWASP, sanitasi input, dan audit dependensi.',
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-EXP-DATA',
    label: 'Data Analytics',
    category: 'exploring',
    badge: 'Learning',
    description: 'Mempelajari visualisasi metrik data terstruktur, visualisasi grafik interaktif, dan analisis alur transaksi.',
    status: 'CONFIRMED',
  },

  // 4. ROBLOX & REAL-WORLD OPERATIONS
  {
    id: 'SKL-RBLX-STUDIO',
    label: 'Roblox Studio & Luau',
    category: 'roblox',
    badge: 'Exploring',
    description: 'Eksplorasi pembentukan ruang 3D, pemodelan parts, serta penulisan skrip event fungsional dasar dengan Luau.',
    projectIds: ['roblox-projects'],
    status: 'CONFIRMED',
  },
  {
    id: 'SKL-OPS-BARISTA',
    label: 'Customer Service & Kasir',
    category: 'operations',
    badge: 'Confirmed',
    description: 'Ketelitian transaksi kasir, pelayanan ramah, dan kerja tim di bawah jam sibuk di 11/12 coffe street Sumedang.',
    projectIds: ['EXP-01'],
    status: 'CONFIRMED',
  },
];
