// src/content/universe.ts

import { SectorInfo } from '@/types/universe';

export const UNIVERSE_SECTORS: SectorInfo[] = [
  {
    id: 'home',
    sectorCode: 'SECTOR 01',
    title: 'XEVRYN CORE',
    shortName: 'CORE',
    sectionId: 'hero',
    tagline: 'Primary Stellar Anchor & System Initialization',
    telemetry: 'RA 18h 42m // DEC +04° 12′ // DIST 0.00 AU',
    coordinates: { x: 0, y: 0, z: 5.5 },
    mapPosition: { x: 50, y: 15 },
    cameraTarget: {
      x: 0,
      y: 0,
      z: 5.5,
      lookAtX: 0,
      lookAtY: 0,
      lookAtZ: 0,
      fov: 45,
      starSpeed: 0.15,
      ambientIntensity: 0.25,
      rimIntensity: 1.8,
    },
    connections: ['identity', 'projects'],
    shortcutKey: '1',
  },
  {
    id: 'identity',
    sectorCode: 'SECTOR 02',
    title: 'IDENTITY ARCHIVE',
    shortName: 'IDENTITY',
    sectionId: 'about',
    tagline: 'Developer DNA & Creative Background Origin',
    telemetry: 'RA 18h 45m // DEC +02° 35′ // DIST 0.42 AU',
    coordinates: { x: 1.8, y: -1.2, z: 5.8 },
    mapPosition: { x: 22, y: 32 },
    cameraTarget: {
      x: 1.5,
      y: -1.0,
      z: 5.6,
      lookAtX: 0.3,
      lookAtY: -0.8,
      lookAtZ: 0,
      fov: 46,
      starSpeed: 0.18,
    },
    connections: ['home', 'experience'],
    shortcutKey: '2',
  },
  {
    id: 'experience',
    sectorCode: 'SECTOR 03',
    title: 'ORBITAL TIMELINE',
    shortName: 'EXPERIENCE',
    sectionId: 'experience',
    tagline: 'Media 3 SMAN 3, Coffee Street & Creative Milestones',
    telemetry: 'RA 18h 51m // DEC -01° 14′ // DIST 0.88 AU',
    coordinates: { x: -2.2, y: -4.5, z: 6.2 },
    mapPosition: { x: 28, y: 52 },
    cameraTarget: {
      x: -1.8,
      y: -4.2,
      z: 6.0,
      lookAtX: -0.5,
      lookAtY: -4.0,
      lookAtZ: 0,
      fov: 48,
      starSpeed: 0.2,
    },
    connections: ['identity', 'media', 'skills'],
    shortcutKey: '3',
  },
  {
    id: 'media',
    sectorCode: 'SECTOR 04',
    title: 'CREATIVE FILM ARCHIVE',
    shortName: 'MEDIA',
    sectionId: 'media3-archive',
    tagline: 'Media 3 SMAN 3 Sumedang Video & Production Vault',
    telemetry: 'RA 18h 55m // DEC -03° 40′ // DIST 1.25 AU',
    coordinates: { x: 2.0, y: -7.5, z: 5.9 },
    mapPosition: { x: 15, y: 72 },
    cameraTarget: {
      x: 1.6,
      y: -7.2,
      z: 5.8,
      lookAtX: 0.4,
      lookAtY: -7.0,
      lookAtZ: 0,
      fov: 47,
      starSpeed: 0.22,
    },
    connections: ['experience'],
    shortcutKey: '4',
  },
  {
    id: 'skills',
    sectorCode: 'SECTOR 05',
    title: 'SKILL NETWORK',
    shortName: 'SKILLS',
    sectionId: 'skills',
    tagline: 'Web Development, Creative Media & Exploring Domains',
    telemetry: 'RA 19h 02m // DEC -06° 22′ // DIST 1.74 AU',
    coordinates: { x: -1.6, y: -11.0, z: 6.0 },
    mapPosition: { x: 50, y: 56 },
    cameraTarget: {
      x: -1.2,
      y: -10.8,
      z: 5.9,
      lookAtX: -0.2,
      lookAtY: -10.6,
      lookAtZ: 0,
      fov: 47,
      starSpeed: 0.24,
    },
    connections: ['experience', 'projects', 'lab'],
    shortcutKey: '5',
  },
  {
    id: 'projects',
    sectorCode: 'SECTOR 06',
    title: 'PROJECT CONSTELLATION',
    shortName: 'PROJECTS',
    sectionId: 'work',
    tagline: 'Solar System of Verified Interactive Applications',
    telemetry: 'RA 19h 12m // DEC -09° 50′ // DIST 2.30 AU',
    coordinates: { x: 1.5, y: -14.2, z: 5.7 },
    mapPosition: { x: 78, y: 40 },
    cameraTarget: {
      x: 1.2,
      y: -14.0,
      z: 5.6,
      lookAtX: 0.2,
      lookAtY: -13.8,
      lookAtZ: 0,
      fov: 46,
      starSpeed: 0.25,
    },
    connections: ['home', 'skills', 'lab'],
    shortcutKey: '6',
  },
  {
    id: 'lab',
    sectorCode: 'SECTOR 07',
    title: 'XEVRYN LAB',
    shortName: 'LAB',
    sectionId: 'lab',
    tagline: 'AI, Automation, Cybersecurity & WebGL Sandbox',
    telemetry: 'RA 19h 22m // DEC -13° 15′ // DIST 2.95 AU',
    coordinates: { x: -1.8, y: -17.5, z: 6.1 },
    mapPosition: { x: 82, y: 68 },
    cameraTarget: {
      x: -1.4,
      y: -17.2,
      z: 5.9,
      lookAtX: -0.3,
      lookAtY: -17.0,
      lookAtZ: 0,
      fov: 47,
      starSpeed: 0.26,
    },
    connections: ['skills', 'projects', 'contact'],
    shortcutKey: '7',
  },
  {
    id: 'contact',
    sectorCode: 'SECTOR 08',
    title: 'COMMUNICATION STATION',
    shortName: 'CONTACT',
    sectionId: 'contact',
    tagline: 'Orbital Transmission Relay & Deep Space Dawn',
    telemetry: 'RA 19h 35m // DEC -17° 05′ // DIST 3.60 AU',
    coordinates: { x: 0, y: -22.0, z: 6.5 },
    mapPosition: { x: 50, y: 88 },
    cameraTarget: {
      x: 0,
      y: -21.8,
      z: 6.2,
      lookAtX: 0,
      lookAtY: -22.2,
      lookAtZ: 0,
      fov: 49,
      starSpeed: 0.15,
      horizonRise: 1.0,
    },
    connections: ['lab', 'media'],
    shortcutKey: '8',
  },
];

export function getSectorById(id: string): SectorInfo {
  return (
    UNIVERSE_SECTORS.find((s) => s.id === id) ||
    UNIVERSE_SECTORS.find((s) => s.sectionId === id) ||
    UNIVERSE_SECTORS[0]
  );
}
